-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 20:23:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola` DEFAULT CHARACTER SET utf8 ;
USE `db_escola` ;

-- -----------------------------------------------------
-- Table `db_escola`.`tb_séries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_séries` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_séries` (
  `id_séries` INT NOT NULL AUTO_INCREMENT,
  `série` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_séries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tb_periodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_periodos` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_periodos` (
  `id_periodos` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_periodos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tb_alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_alunos` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_alunos` (
  `id_alunos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `séries_id` INT NOT NULL,
  `periodos_id` INT NOT NULL,
  `nota` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`id_alunos`),
  INDEX `fk_tb_alunos_tb_séries_idx` (`séries_id` ASC) VISIBLE,
  INDEX `fk_tb_alunos_tb_periodos1_idx` (`periodos_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_alunos_tb_séries`
    FOREIGN KEY (`séries_id`)
    REFERENCES `db_escola`.`tb_séries` (`id_séries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_alunos_tb_periodos1`
    FOREIGN KEY (`periodos_id`)
    REFERENCES `db_escola`.`tb_periodos` (`id_periodos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_séries (série) VALUE ("Infantil");
INSERT INTO tb_séries (série) VALUE ("2ª série");
INSERT INTO tb_séries (série) VALUE ("3ª série");
INSERT INTO tb_séries (série) VALUE ("4ª série");
INSERT INTO tb_séries (série) VALUE ("5ª série");
INSERT INTO tb_séries (série) VALUE ("6ª série");
INSERT INTO tb_séries (série) VALUE ("7ª série");
INSERT INTO tb_séries (série) VALUE ("8ª série");
INSERT INTO tb_séries (série) VALUE ("9ª série");
INSERT INTO tb_séries (série) VALUE ("1º ano");
INSERT INTO tb_séries (série) VALUE ("2º ano");
INSERT INTO tb_séries (série) VALUE ("3º ano");

INSERT INTO tb_periodos (periodo) VALUE ("Matutino");
INSERT INTO tb_periodos (periodo) VALUE ("Vespertino");
INSERT INTO tb_periodos (periodo) VALUE ("Noturno");

INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('João', '12', '3', '8');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Maria', '4', '1', '6');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('José', '6', '2', '5');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Antonio', '9', '1', '5');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Gabriel', '1', '1', '7');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Vitor', '12', '3', '8');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Vinicius', '7', '1', '4');
INSERT INTO `db_escola`.`tb_alunos` (`Nome`, `séries_id`, `periodos_id`, `nota`) VALUES ('Thiago', '8', '2', '8');

SELECT * FROM tb_alunos;
-- SELECT * FROM tb_alunos WHERE nota < 7;
-- SELECT * FROM tb_alunos WHERE nota >= 7;