-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 11:04:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cursoDaMinhaVida` DEFAULT CHARACTER SET utf8 ;
USE `db_cursoDaMinhaVida` ;

-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cursoDaMinhaVida`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `modo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cursoDaMinhaVida`.`tb_curso` ;

CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `matéria` VARCHAR(45) NOT NULL,
  `modo_id` INT NOT NULL,
  `professor` VARCHAR(45) NOT NULL,
  `preço` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_tb_curso_tb_categoria_idx` (`modo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_curso_tb_categoria`
    FOREIGN KEY (`modo_id`)
    REFERENCES `db_cursoDaMinhaVida`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Síncrono', 'Fundamental');
INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Síncrono', 'Médio');
INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Síncrono', 'Superior');
INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Assincrono', 'Fundamental');
INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Assincrono', 'Médio');
INSERT INTO `db_cursodaminhavida`.`tb_categoria` (`modo`, `nivel`) VALUES ('Assincrono', 'Superior');

INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Matemática I', '1', 'Zé', '30');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Matemática II', '2', 'Zé', '50');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Matemática III', '3', 'Zé', '70');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Português I', '4', 'Noslen', '30');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Português II', '5', 'Noslen', '50');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Português III', '6', 'Noslen', '70');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Programação I', '3', 'Luís', '0');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`matéria`, `modo_id`, `professor`, `preço`) VALUES ('Programação II', '3', 'Boaz', '0');

-- SELECT * FROM tb_curso;

-- SELECT * FROM tb_curso WHERE preço >= 50;
-- SELECT * FROM tb_curso WHERE preço>= 3 and preço <= 60;
-- SELECT * FROM tb_curso WHERE matéria LIKE "%J%";
-- SELECT tb_curso.matéria, tb_categoria.modo, tb_categoria.nivel, tb_curso.professor, tb_curso.preço FROM tb_curso INNER JOIN tb_categoria ON tb_curso.modo_id = tb_categoria.id_categoria;
-- SELECT tb_curso.matéria, tb_categoria.modo, tb_categoria.nivel, tb_curso.professor, tb_curso.preço FROM tb_curso INNER JOIN tb_categoria ON tb_curso.modo_id = tb_categoria.id_categoria WHERE tb_curso.matéria LIKE "Programação%";