-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 09:45:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_carnes` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_carnes` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cidade_das_carnes`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `disponibilidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cidade_das_carnes`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `preço` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_cidade_das_carnes`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_cidade_das_carnes`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Carne Bovina', true);
INSERT INTO `db_cidade_das_carnes`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Carne Suína', true);
INSERT INTO `db_cidade_das_carnes`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Frango', true);
INSERT INTO `db_cidade_das_carnes`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Peixe', false);

INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Picanha', 'Friboi', 1, 80);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Costela ', 'Seara', 2, 50);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Carne moída', 'Montana', 1, 24);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Coxa com sobrecoxa', 'Seara', 3, 30);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Hamburguer', 'Friboi', 1, 16);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Salmão', 'Qualitá', 4, 90);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Filé de merluza', 'Qualitá', 4, 35);
INSERT INTO `db_cidade_das_carnes`.`tb_produto` (`nome`, `marca`, `categoria_id`, `preço`) VALUES ('Lombo', 'Montana', 2, 40);

-- SELECT * FROM tb_produto;

-- SELECT * FROM tb_produto WHERE preço >= 60;
-- SELECT * FROM tb_produto WHERE nome LIKE "%C%";
-- SELECT tb_produto.nome,  tb_produto.marca, tb_categoria.tipo, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_categoria.id_categoria = tb_produto.categoria_id;
-- SELECT tb_produto.nome,  tb_produto.marca, tb_categoria.tipo, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_categoria.id_categoria = tb_produto.categoria_id WHERE tb_produto.marca = "Friboi";