-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 19:20:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rhempresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rhempresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rhempresa` DEFAULT CHARACTER SET utf8 ;
USE `db_rhempresa` ;

-- -----------------------------------------------------
-- Table `db_rhempresa`.`tb_funcionarie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_rhempresa`.`tb_funcionarie` ;

CREATE TABLE IF NOT EXISTS `db_rhempresa`.`tb_funcionarie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NULL,
  `cargo_id` INT NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rhempresa`.`tb_cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_rhempresa`.`tb_cargo` ;

CREATE TABLE IF NOT EXISTS `db_rhempresa`.`tb_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_cargo (cargos) value ("desenvolvedor java júnior");
INSERT INTO tb_cargo (cargos) value ("desenvolvedor java pleno");
INSERT INTO tb_cargo (cargos) value ("desenvolvedor java senior");
INSERT INTO tb_cargo (cargos) value ("desenvolvedor java master");

INSERT INTO tb_funcionarie (nome, CPF, cargo_id, salario) values ("João", 123, 4, 7500);
INSERT INTO tb_funcionarie (nome, CPF, cargo_id, salario) values ("Maria", 135, 1,1800);
INSERT INTO tb_funcionarie (nome, CPF, cargo_id, salario) values ("Guilherme", 157, 1, 1800);
INSERT INTO tb_funcionarie (nome, CPF, cargo_id, salario) values ("Gabriel", 246, 2, 3000);
INSERT INTO tb_funcionarie (nome, CPF, cargo_id, salario) values ("Vitor", 357, 3, 4500);

 SELECT * FROM tb_funcionarie
-- SELECT * FROM tb_funcionarie WHERE salario < 2000;
-- SELECT * FROM tb_funcionarie WHERE salario >= 2000;