-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 10:12:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_construindo_a_nossa_vida` DEFAULT CHARACTER SET utf8 ;
USE `db_construindo_a_nossa_vida` ;

-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_construindo_a_nossa_vida`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(45) NOT NULL,
  `disponibilidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_construindo_a_nossa_vida`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `setor_id` INT NOT NULL,
  `quantidade_disponivel` INT NOT NULL,
  `preço` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`setor_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`setor_id`)
    REFERENCES `db_construindo_a_nossa_vida`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_construindo_a_nossa_vida`.`tb_categoria` (`setor`, `disponibilidade`) VALUES ('Materiais de construção', 'true');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_categoria` (`setor`, `disponibilidade`) VALUES ('Hidraulica', 'true');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_categoria` (`setor`, `disponibilidade`) VALUES ('Elétrica', 'true');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_categoria` (`setor`, `disponibilidade`) VALUES ('Cerâmica', 'false');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_categoria` (`setor`, `disponibilidade`) VALUES ('Pintura', 'false');

INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Cimento', 'Sincomavi', '1', '100', '20');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Tijolos', 'Martins', '1', '1000', '2.50');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Chuveiro', 'Lorenzetti', '2', '50', '150');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Pia', 'Granito', '2', '30', '350');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Lâmpadas', 'Philips', '3', '50', '7.50');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Interruptores', 'Siemens', '3', '80', '4.50');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Tinta', 'Coral', '5', '0', '200');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produto` (`nome`, `marca`, `setor_id`, `quantidade_disponivel`, `preço`) VALUES ('Piso cerâmica', 'Portinari', '4', '0', '5');

-- SELECT * FROM tb_produto;

-- SELECT * FROM tb_produto WHERE preço >= 50;
-- SELECT * FROM tb_produto WHERE preço <= 60 and preço >= 3;
-- SELECT * FROM tb_produto WHERE nome LIKE "%C%";
-- SELECT tb_produto.nome, tb_produto.marca, tb_categoria.setor, tb_produto.quantidade_disponivel, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_produto.setor_id = tb_categoria.id_categoria;
-- SELECT tb_produto.nome, tb_produto.marca, tb_categoria.setor, tb_produto.quantidade_disponivel, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_produto.setor_id = tb_categoria.id_categoria WHERE tb_categoria.setor = "Hidraulica";