-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 14:28:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia_do_bem`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `disponibilidade` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia_do_bem`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `tipo_id` INT NOT NULL,
  `preço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `db_farmacia_do_bem`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_farmacia_do_bem`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Remédio', true);
INSERT INTO `db_farmacia_do_bem`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Cosmético', true);
INSERT INTO `db_farmacia_do_bem`.`tb_categoria` (`tipo`, `disponibilidade`) VALUES ('Produtos variados', true);

INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Dipirona', 'Bayer', '1', '2');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Neosaldina', 'Eurofarma', '1', '4');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Perfume', 'Avon', '2', '70');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Maquiagem', 'Avon', '2', '40');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Desodorante', 'Rexona', '3', '12');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Desodorante', 'Monange', '3', '10');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Xarope', 'Eurofarma', '1', '20');
INSERT INTO `db_farmacia_do_bem`.`tb_produto` (`nome`, `marca`, `tipo_id`, `preço`) VALUES ('Vitamina C', 'Bayer', '3', '8');

-- SELECT * FROM tb_produto;

-- SELECT * FROM tb_produto WHERE preço >= 50;
-- SELECT * FROM tb_produto WHERE preço BETWEEN 3 and 60;
-- SELECT * FROM tb_produto WHERE nome LIKE "%B%";
-- SELECT tb_produto.nome, tb_produto.marca, tb_categoria.tipo, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_produto.tipo_id = tb_categoria.id_categoria;
-- SELECT tb_produto.nome, tb_produto.marca, tb_categoria.tipo, tb_produto.preço FROM tb_produto INNER JOIN tb_categoria ON tb_produto.tipo_id = tb_categoria.id_categoria WHERE tb_categoria.tipo = "Cosmético";