-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 14:01:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_classe` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id_classe` INT NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_personagem` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `poder_de_ataque` INT NOT NULL,
  `poder_de_defesa` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id_personagem`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`classe_id`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Espadachim', 'Combate direto');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Mago', 'Combate à distância');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Sacerdote', 'Combate à distância');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Bardo', 'Combate à distância');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Druidas', 'Combate direto');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Arqueiro', 'Combate à distância');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Templário', 'Combate direto');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Ranger', 'Combate direto');
INSERT INTO `db_generation_game_online`.`tb_classe` (`classe`, `tipo`) VALUES ('Rogue', 'Combate direto');

INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('Rem', '2000', '800', '2');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('Rob', '1400', '1400', '5');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`,`classe_id`) VALUES ('MrSpringles', '1200', '1600', '7');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('Hukaku', '600', '1000', '4');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('Gui', '1600', '1200', '1');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('Maria', '1800', '1000', '3');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `poder_de_ataque`, `poder_de_defesa`, `classe_id`) VALUES ('José', '1600', '1200', '9');

-- SELECT * FROM tb_personagem;

-- SELECT * FROM tb_personagem WHERE poder_de_ataque  >= 2000;
-- SELECT * FROM tb_personagem WHERE poder_de_defesa >= 1000 and poder_de_defesa <= 2000;
-- SELECT * FROM tb_personagem WHERE nome LIKE "%C%";
-- SELECT tb_personagem.nome, tb_personagem.poder_de_ataque, tb_personagem.poder_de_defesa, tb_classe.classe, tb_classe.tipo FROM tb_personagem INNER JOIN tb_classe ON tb_classe.id_classe = tb_personagem.classe_id;
-- SELECT tb_personagem.nome, tb_personagem.poder_de_ataque, tb_personagem.poder_de_defesa, tb_classe.classe, tb_classe.tipo FROM tb_personagem INNER JOIN tb_classe ON tb_classe.id_classe = tb_personagem.classe_id WHERE tb_classe.classe LIKE "%mago%";